title: Sujit Thakur
logo: asset/headshot_circle.png
#description: Data Scientist with 4+ years experience and ML  Hackathon - 2024 Winner
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0


