
title: Sujit Thakur
logo: /asset/headshot_circle.png
description: Data Scientist with 4+ years experience and Hackathon - Machine Learning 2024 Winner
show_downloads: true
theme: jekyll-theme-minimal
